### PR TITLE
Ad0: Ruby IT Sat campaign

### PR DESCRIPTION
**Pull request by rrader**
Ad image

### CODE REVIEW

**Comment by rrader** [comment]
I'm sorry, that was added by mistake

**Comment by moklick** [comment]
:smile: what are you guys doing here?

**Comment by rrader** [comment]
@moklick heh, we forked this theme for our site, I wanted to make PR to the fork but Github uses your repo by default ;)

Thank you for the theme BTW :+1:

**Comment by moklick** [comment]
no problem :)

**Pull request closed without merging**
